### ISSUE TITLE
クラッシュしたら起こす

### ISSUE THREAD

**Issue by masutaka** [feedforce/feedforce-ruboty#17]
時々落ちているので、簡単なスクリプトでラッピングしようかな。
今日は以下で落ちてた。

```
Mar 01 17:29:13 feedforce-ruboty app/bot.1:  /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/connection/ruby.rb:152:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError) 
```

これとは別に、バイトコードを含むメッセージをポストするとクラッシュすることが分かっているので、あとでPR出す。

「ほげ」と「ふが」の間にバイトコード`^P`を入れたらクラッシュ。`String#inspect`でイケルかと。

```
Mar 03 18:50:18 feedforce-ruboty app/bot.1:  /app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rexml/text.rb:138:in `block in check': Illegal character "\u0010" in raw string "ほげふが" (RuntimeError) 
```

**Comment by masutaka** [comment]
> これとは別に、バイトコードを含むメッセージをポストするとクラッシュすることが分かっているので、あとでPR出す。

[マージされて](https://github.com/r7kamura/xrc/pull/11)、[リリースもされた](https://github.com/r7kamura/xrc/releases/tag/v0.1.5)。

**Comment by masutaka** [comment]
Herokuは落ちたら再起動してくれたりくれなかったりして良くわからない。
一旦このIssueはクローズする。
